version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Flask Configuration
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_APP=main.py
      
      # Database (otomatik bağlantı)
      - DATABASE_URL=postgresql://ipam_user:${POSTGRES_PASSWORD:-ipam_secure_2024}@db:5432/ipam_db
      
      # Security
      - SECRET_KEY=${SECRET_KEY:-change-this-super-secret-key-in-production}
      - SESSION_SECRET=${SESSION_SECRET:-change-this-session-secret-too}
      
      # Application Settings
      - APP_NAME=IPAM Platform
      - APP_PORT=5000
      - APP_HOST=0.0.0.0
      
      # Locale
      - DEFAULT_LOCALE=tr_TR
      - TIMEZONE=Europe/Istanbul
      
      # Logging
      - LOG_TO_STDOUT=1
      - LOG_LEVEL=INFO
    
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ipam-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        echo 'Creating database tables...' &&
        python -c 'from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()' &&
        echo 'Seeding initial data...' &&
        python seed_data.py &&
        echo 'Starting IPAM Platform...' &&
        gunicorn --bind 0.0.0.0:5000 --workers 3 --threads 2 --timeout 120 --access-logfile - --error-logfile - main:app
      "

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=ipam_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ipam_secure_2024}
      - POSTGRES_DB=ipam_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ipam-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ipam_user -d ipam_db"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  ipam-network:
    driver: bridge
